/* date = November 25th 2021 2:58 pm */

#ifndef DC_CONFIG_H
#define DC_CONFIG_H

#define INITIAL_WINDOW_COORD_X (1000)
#define INITIAL_WINDOW_COORD_Y (10)
#define INITIAL_WINDOW_WIDTH  (600)
#define INITIAL_WINDOW_HEIGHT (1000)

#define PERMANENT_STORAGE_SIZE MEGABYTES(64)
#define TRANSIENT_STORAGE_SIZE MEGABYTES(64)
#define DEBUG_CONSOLE_BUFFER_SIZE       (4096)

#define RENDERER_OPENGL   1
#define RENDERER_SOFTWARE 0
#define RENDERER_D3D11    0


#endif //DC_CONFIG_H
