/* date = January 8th 2021 9:01 pm */

#ifndef FLIGHTCONTROL_PROGRAM_OPTIONS_H
#define FLIGHTCONTROL_PROGRAM_OPTIONS_H


#define INITIAL_WINDOW_COORD_X (10)
#define INITIAL_WINDOW_COORD_Y (10)
#define INITIAL_WINDOW_WIDTH  (600)
#define INITIAL_WINDOW_HEIGHT (1000)

#define PERMANENT_STORAGE_SIZE MEGABYTES(64)
#define DEBUG_CONSOLE_BUFFER_SIZE       (4096)

#endif //FLIGHTCONTROL_PROGRAM_OPTIONS_H
